sudo: false
language: objective-c
osx_image: xcode7.1

xcode_project: Swiftification.xcodeproj
xcode_scheme: Swiftification
xcode_sdk: iphonesimulator9.1

script:
- xcodebuild clean build test -project Swiftification.xcodeproj -scheme Swiftification -sdk iphonesimulator9.1 -destination "OS=9.1,name=iPhone 5"
