sudo: false
language: swift
osx_image: xcode9
notifications:
  slack: lyokotech:7AmemNHORB2ShidELPFrYeUO
  email: false
script:
- xcodebuild clean build test -project Swiftification.xcodeproj -scheme Swiftification -sdk iphonesimulator -destination "OS=11.0,name=iPhone 8,platform=iOS Simulator"
